In [813]:

from datetime import timedelta, date
import numpy as np

import string 
import pandas as pd
import functools

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2019, 1, 1)
end_dt = date(2019, 12, 31)
dt_range = []

for dt in daterange(start_dt, end_dt):
    dt_range.append(dt.strftime("%Y-%m-%d"))


In [814]:
#Generating 5000 instances of each acitivity 

# txn acitivity 
act_date = np.random.choice(dt_range,5000)
phone_number =  np.random.choice(range(1,1001),5000)
act_id  = np.random.choice(range(1,5001),5000)
data = {
        'phone' : phone_number,
        'date' : act_date,
        'id' : act_id
       }
df = pd.DataFrame(data,columns = ['phone','date','id'])
colx =  ['phone','date','id']
tx_df = df.reindex(columns=colx)
tx_df['act'] = 'Txn'

In [815]:
act_date = np.random.choice(dt_range,5000)
phone_number =  np.random.choice(range(1,1001),5000)
act_id  = np.random.choice(range(1,5001),5000)
data = {
        'phone' : phone_number,
        'date' : act_date,
        'id' : act_id
       }
df = pd.DataFrame(data,columns = ['phone','date','id'])
colx =  ['phone','date','id']
app_df = df.reindex(columns=colx)
app_df['act'] = 'App'

In [816]:
act_date = np.random.choice(dt_range,5000)
phone_number =  np.random.choice(range(1,1001),5000)
act_id = np.random.choice(range(1,5001),5000)
data = {
        'phone' : phone_number,
        'date' : act_date,
        'id' : act_id
       }
df = pd.DataFrame(data,columns = ['phone','date','id'])
colx =  ['phone','date','id']
sms_df = df.reindex(columns=colx)
sms_df['act'] = 'SMS'

In [817]:
act_date = np.random.choice(dt_range,5000)
phone_number =  np.random.choice(range(1,1001),5000)
act_id = np.random.choice(range(1,5001),5000)
data = {
        'phone' : phone_number,
        'date' : act_date,
        'id' : act_id
       }
df = pd.DataFrame(data,columns = ['phone','date','id'])
colx =  ['phone','date','id']
web_df = df.reindex(columns=colx)
web_df['act'] = 'WEB'

In [818]:
act_date = np.random.choice(dt_range,5000)
phone_number =  np.random.choice(range(1,1001),5000)
act_id = np.random.choice(range(1,5001),5000)
data = {
        'phone' : phone_number,
        'date' : act_date,
        'id' : act_id
       }
df = pd.DataFrame(data,columns = ['phone','date','id'])
colx =  ['phone','date','id']
email_df = df.reindex(columns=colx)
email_df['act'] = 'email'

In [819]:
 master = pd.concat([tx_df, app_df,sms_df,web_df,email_df])

In [820]:
master = master.reindex()
master.head()
#master.info()

phone        date    id  act
0    661  2019-01-14  3369  Txn
1     47  2019-09-24  4946  Txn
2    557  2019-06-09  4927  Txn
3    319  2019-04-17   308  Txn
4    810  2019-11-05   941  Txn

In [821]:
master = master.sort_values(by = ['phone','date'])

In [822]:
master_backup = master
master

phone        date    id    act
2275      1  2019-01-09  3819    Txn
2728      1  2019-01-20  4103    App
3212      1  2019-01-29  3359    Txn
1341      1  2019-02-18  1908    WEB
3671      1  2019-02-19  4037    WEB
...     ...         ...   ...    ...
3000   1000  2019-11-12  3994    App
3599   1000  2019-11-13   189    WEB
2592   1000  2019-11-16  3284    App
1908   1000  2019-11-16  1623  email
2705   1000  2019-12-21  3925    WEB

[25000 rows x 4 columns]

In [823]:
tx_temp = master[master.act=='Txn']
act_temp = master[master.act!='Txn']

In [824]:
tx_temp['date_lag'] = tx_temp.groupby(['phone'])['date'].shift(1)
tx_temp['lag_id'] = tx_temp['id'].shift(1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [825]:
import numpy as np
tx_temp.loc[tx_temp.date_lag.isnull(),'lag_id'] = np.nan

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [826]:
tx_temp.loc[tx_temp.lag_id.isnull(),'lag_id'] = tx_temp.loc[tx_temp.lag_id.isnull(),'id'] 
tx_temp.loc[tx_temp.date_lag.isnull(),'date_lag'] = '1970-01-01'

In [827]:
tx_temp['date'] = pd.to_datetime(tx_temp['date']).dt.date
tx_temp['date_lag'] = pd.to_datetime(tx_temp['date_lag']).dt.date
tx_temp

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


phone        date    id  act    date_lag  lag_id
2275      1  2019-01-09  3819  Txn  1970-01-01  3819.0
3212      1  2019-01-29  3359  Txn  2019-01-09  3819.0
3164      1  2019-03-21  1592  Txn  2019-01-29  3359.0
4240      1  2019-06-08  2117  Txn  2019-03-21  1592.0
4327      1  2019-06-11  1678  Txn  2019-06-08  2117.0
...     ...         ...   ...  ...         ...     ...
1641   1000  2019-05-08  2057  Txn  2019-03-27  2746.0
4241   1000  2019-06-10  1026  Txn  2019-05-08  2057.0
3579   1000  2019-07-29  4293  Txn  2019-06-10  1026.0
244    1000  2019-08-10  2955  Txn  2019-07-29  4293.0
88     1000  2019-10-19  1518  Txn  2019-08-10  2955.0

[5000 rows x 6 columns]

In [828]:
act_temp

phone        date    id    act
2728      1  2019-01-20  4103    App
1341      1  2019-02-18  1908    WEB
3671      1  2019-02-19  4037    WEB
4638      1  2019-04-06  3760  email
2646      1  2019-04-16  2758    SMS
...     ...         ...   ...    ...
3000   1000  2019-11-12  3994    App
3599   1000  2019-11-13   189    WEB
2592   1000  2019-11-16  3284    App
1908   1000  2019-11-16  1623  email
2705   1000  2019-12-21  3925    WEB

[20000 rows x 4 columns]

In [829]:
import pandasql as ps

sqlcode = '''
select a.phone,a.date,a.id,a.act,b.date as txn_dt,b.id as txn_id
from act_temp a
left join tx_temp b on a.phone = b.phone and a.date <= b.date and a.date > b.date_lag
'''

newdf = ps.sqldf(sqlcode,locals())

In [830]:
#tx_temp[tx_temp.phone==1000]
newdf

phone        date    id    act      txn_dt  txn_id
0          1  2019-01-20  4103    App  2019-01-29  3359.0
1          1  2019-02-18  1908    WEB  2019-03-21  1592.0
2          1  2019-02-19  4037    WEB  2019-03-21  1592.0
3          1  2019-04-06  3760  email  2019-06-08  2117.0
4          1  2019-04-16  2758    SMS  2019-06-08  2117.0
...      ...         ...   ...    ...         ...     ...
19995   1000  2019-11-12  3994    App        None     NaN
19996   1000  2019-11-13   189    WEB        None     NaN
19997   1000  2019-11-16  3284    App        None     NaN
19998   1000  2019-11-16  1623  email        None     NaN
19999   1000  2019-12-21  3925    WEB        None     NaN

[20000 rows x 6 columns]

In [831]:
from datetime import date
newdf['date_diff'] = (pd.to_datetime(newdf['txn_dt']) - pd.to_datetime(newdf['date'])).dt.days

In [832]:
newdf['txn_break'] = 0
newdf.loc[newdf.date_diff <14,'txn_break'] = 1
#xdx = newdf[newdf.date_diff>=14]

In [833]:
newdf.head(-50)

phone        date    id    act      txn_dt  txn_id  date_diff  \
0          1  2019-01-20  4103    App  2019-01-29  3359.0        9.0   
1          1  2019-02-18  1908    WEB  2019-03-21  1592.0       31.0   
2          1  2019-02-19  4037    WEB  2019-03-21  1592.0       30.0   
3          1  2019-04-06  3760  email  2019-06-08  2117.0       63.0   
4          1  2019-04-16  2758    SMS  2019-06-08  2117.0       53.0   
...      ...         ...   ...    ...         ...     ...        ...   
19945    998  2019-09-23  1354    App  2019-11-25   416.0       63.0   
19946    998  2019-10-22  1595  email  2019-11-25   416.0       34.0   
19947    998  2019-10-26  2912    App  2019-11-25   416.0       30.0   
19948    998  2019-11-06  3184    App  2019-11-25   416.0       19.0   
19949    998  2019-11-07  2805    SMS  2019-11-25   416.0       18.0   

       txn_break  
0              1  
1              0  
2              0  
3              0  
4              0  
...          ...  
19945          0  
19946          0  
19947          0  
19948          0  
19949          0  

[19950 rows x 8 columns]

In [834]:
tx_temp.sort_values(by = ['phone','date'],ascending = False).head(5)

phone        date    id  act    date_lag  lag_id
88     1000  2019-10-19  1518  Txn  2019-08-10  2955.0
244    1000  2019-08-10  2955  Txn  2019-07-29  4293.0
3579   1000  2019-07-29  4293  Txn  2019-06-10  1026.0
4241   1000  2019-06-10  1026  Txn  2019-05-08  2057.0
1641   1000  2019-05-08  2057  Txn  2019-03-27  2746.0

In [835]:
newdf = newdf.sort_values(by = ['phone','date'],ascending = False)
#newdf.head(50)
newdf.loc[newdf.txn_dt.isnull(),'txn_dt'] = '1970-01-01'
newdf
newdf['ntp_break'] = 0

In [836]:
#newdf.shape[0]
#newdf.iloc[20000-1,:]
break_dt = newdf.date.max()
from datetime import datetime
date_format = "%Y-%m-%d"
#if df[0] la flag == 0 start point =1 and break_dt = 0 date

for i in range(0,newdf.shape[0]):
    #print(i)
    if(newdf.iloc[i,7] == 1):
        continue
    else:
        if(newdf.iloc[i-1,7]==1):
            break_dt = newdf.iloc[i,1]
            newdf.iloc[i,4] = break_dt
            newdf.iloc[i,8] = 1
        elif(newdf.iloc[i-1,0]!=newdf.iloc[i,0]):
            break_dt = newdf.iloc[i,1]
            newdf.iloc[i,4] = break_dt
            newdf.iloc[i,8] = 1
        elif(((datetime.strptime(break_dt, date_format) - datetime.strptime(newdf.iloc[i,1], date_format)).days > 15)):
            break_dt = newdf.iloc[i,1]
            newdf.iloc[i,4] = break_dt
            newdf.iloc[i,8] = 1
        else:
            newdf.iloc[i,4] = break_dt
    #print('for i = \n' + str(i))
    #print(newdf.iloc[i,:])
    #print(break_dt)
    #print(newdf.iloc[i,4])
    #print((datetime.strptime(break_dt, date_format) - datetime.strptime(newdf.iloc[i,4], date_format)))
    

In [837]:
newdf['date_diff'] = (pd.to_datetime(newdf['txn_dt']) - pd.to_datetime(newdf['date'])).dt.days
#newdf = newdf.head(10)
newdf.sort_values(by = ['phone','date']).head(5)
# Write and store this file - heavy procesing before this is needed again

phone        date    id    act      txn_dt  txn_id  date_diff  txn_break  \
0      1  2019-01-20  4103    App  2019-01-29  3359.0          9          1   
1      1  2019-02-18  1908    WEB  2019-02-19  1592.0          1          0   
2      1  2019-02-19  4037    WEB  2019-02-19  1592.0          0          0   
3      1  2019-04-06  3760  email  2019-04-17  2117.0         11          0   
4      1  2019-04-16  2758    SMS  2019-04-17  2117.0          1          0   

   ntp_break  
0          0  
1          0  
2          1  
3          0  
4          0

In [838]:
dtypes = np.dtype([
          ('customer', int),
          ('transition_matrix', str)
          ])
data = np.empty(0, dtype=dtypes)
cust_master = pd.DataFrame(data)
cust_master


Empty DataFrame
Columns: [customer, transition_matrix]
Index: []

In [839]:
#row = ['iname', 's']
#cust_master.loc[len(cust_master)] = row
#cust_master
#from_axis = {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 , 'start' : 4}
#to_axis = {'sms': 0, 'email': 1, 'app': 2, 'web':3 , 'txn' : 4}
#from_axis[newdf.iloc[0,3]]
#conv_act =  np.zeros((1, 4))

In [840]:
#conv_act =  np.zeros((5, 6))
conv_act[0][from_axis['App']]+=1
conv_act

array([[1., 1., 1., 1., 3., 1.],
       [0., 0., 0., 2., 0., 2.],
       [2., 2., 0., 1., 1., 3.],
       [0., 0., 0., 1., 0., 5.],
       [4., 1., 9., 1., 2., 0.]])

In [841]:
dtypes = np.dtype([
          ('customer', int),
          ('transition_matrix', object)
          ])
newdf = newdf.sort_values(by = ['phone','date'])

In [842]:
tx_temp = tx_temp.iloc[:,0:4]
tx_temp['txn_dt'] = tx_temp['date']
tx_temp['txn_id'] = tx_temp['id']
tx_temp['date_diff'] = 0
tx_temp['txn_break'] = 2
tx_temp['ntp_break'] = 0
tx_temp

phone        date    id  act      txn_dt  txn_id  date_diff  txn_break  \
2275      1  2019-01-09  3819  Txn  2019-01-09    3819          0          2   
3212      1  2019-01-29  3359  Txn  2019-01-29    3359          0          2   
3164      1  2019-03-21  1592  Txn  2019-03-21    1592          0          2   
4240      1  2019-06-08  2117  Txn  2019-06-08    2117          0          2   
4327      1  2019-06-11  1678  Txn  2019-06-11    1678          0          2   
...     ...         ...   ...  ...         ...     ...        ...        ...   
1641   1000  2019-05-08  2057  Txn  2019-05-08    2057          0          2   
4241   1000  2019-06-10  1026  Txn  2019-06-10    1026          0          2   
3579   1000  2019-07-29  4293  Txn  2019-07-29    4293          0          2   
244    1000  2019-08-10  2955  Txn  2019-08-10    2955          0          2   
88     1000  2019-10-19  1518  Txn  2019-10-19    1518          0          2   

      ntp_break  
2275          0  
3212          0  
3164          0  
4240          0  
4327          0  
...         ...  
1641          0  
4241          0  
3579          0  
244           0  
88            0  

[5000 rows x 9 columns]

In [843]:
newdf = pd.concat([tx_temp, newdf])
newdf = newdf.sort_values(by = ['phone','date'])
newdf = newdf.reset_index(drop=True)
newdf
#newdf.loc[i,:]
#newdf.shape

phone        date    id    act      txn_dt  txn_id  date_diff  \
0          1  2019-01-09  3819    Txn  2019-01-09  3819.0          0   
1          1  2019-01-20  4103    App  2019-01-29  3359.0          9   
2          1  2019-01-29  3359    Txn  2019-01-29  3359.0          0   
3          1  2019-02-18  1908    WEB  2019-02-19  1592.0          1   
4          1  2019-02-19  4037    WEB  2019-02-19  1592.0          0   
...      ...         ...   ...    ...         ...     ...        ...   
24995   1000  2019-11-12  3994    App  2019-11-16     NaN          4   
24996   1000  2019-11-13   189    WEB  2019-11-16     NaN          3   
24997   1000  2019-11-16  3284    App  2019-11-16     NaN          0   
24998   1000  2019-11-16  1623  email  2019-11-16     NaN          0   
24999   1000  2019-12-21  3925    WEB  2019-12-21     NaN          0   

       txn_break  ntp_break  
0              2          0  
1              1          0  
2              2          0  
3              0          0  
4              0          1  
...          ...        ...  
24995          0          0  
24996          0          0  
24997          0          1  
24998          0          0  
24999          0          1  

[25000 rows x 9 columns]

In [844]:
dtypes = np.dtype([
          ('customer', int),
          ('transition_matrix', object)
          ])
data = np.empty(0, dtype=dtypes)
cust_master = pd.DataFrame(data)

from_axis = {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 , 'start' : 4}
to_axis = {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 , 'Txn' : 4}

cust_pres = newdf.iloc[0,0]
path_pres = newdf.iloc[0,4]
conv_act =  np.zeros((5,6))

start = 1
g = 0
import time
start_time = time.time()

for i in range(0,newdf.shape[0]):
        #print(cust_pres)
        #print(conv_act)
        if(newdf.iloc[i,0] != cust_pres):
            #print(cust_pres)

            # Process and write to cust_master for PREVIOUS CUSTOMER
            # Use inline lambda function to increase performance 
            # df.apply(lambda row : add(row['A'], row['B'], row['C']), axis = 1) 
            
            
            
            row = [str(cust_pres), conv_act.tostring()]
            cust_master.loc[len(cust_master)] = row
            
            
            #del start_idx
            del cust_pres
            del conv_act
            
            cust_pres = newdf.iloc[i,0]
            conv_act =  np.zeros((5,6))
            # start -> curr
            conv_act[4,to_axis[newdf.iloc[i,3]]]+=1
            start = 0
            
            if(newdf.loc[i,'txn_break'] == 2):
                start=1
                continue
            if(newdf.loc[i,'ntp_break'] == 1):
                start=1
                #curr->null
                conv_act[from_axis[newdf.iloc[i,3]],5]+=1
                continue
                
        if(start == 1):
            if(newdf.loc[i,'txn_break']==2):
                conv_act[4,to_axis[newdf.iloc[i,3]]]+=1
                start = 1
                continue
            elif(newdf.loc[i,'ntp_break'] == 1):
                #start->curr
                conv_act[4,to_axis[newdf.iloc[i,3]]]+=1
                #curr -> null
                conv_act[from_axis[newdf.iloc[i,3]],5]+=1
                start = 1
                continue
            else:
                # start = curr
                conv_act[4,to_axis[newdf.iloc[i,3]]]+=1
                # curr -> next
                conv_act[from_axis[newdf.iloc[i,3]],to_axis[newdf.iloc[i+1,3]]]+=1
                start = 0
                continue
                
        if(newdf.loc[i,'txn_break'] == 1):
            # add to matrix
            conv_act[from_axis[newdf.iloc[i,3]],to_axis[newdf.iloc[i+1,3]]]+=1
            continue
            
        if(newdf.loc[i,'txn_break']==2):
            start = 1
            continue 
            
        if(newdf.loc[i,'ntp_break'] == 1):
            # curr -> null
            conv_act[from_axis[newdf.iloc[i,3]],5]+=1
            start = 1
            continue
            
        if(newdf.loc[i,'ntp_break'] == 0):
            # add to matrix
            conv_act[from_axis[newdf.iloc[i,3]],to_axis[newdf.iloc[i+1,3]]]+=1
            continue
    
    ###### Wrtie for the last customer !######
row = [str(cust_pres), conv_act.tostring()]
cust_master.loc[len(cust_master)] = row
time.time() - start_time

7.002803087234497

In [845]:
def matrix_transform(conv_act):
    conv_act = np.fromstring(conv_act,float).reshape(5,6)
    start_idx = conv_act[-1].copy()
    for i in range(0,conv_act.shape[1]):
        conv_act[:,i] = conv_act[:,i]/(conv_act[:,i].sum())
    conv_act[-1] = start_idx/start_idx.sum()
    return(conv_act.tostring())

#cust_master['transition_matrix'].apply(lambda row : matrix_transform(row)) 
#cust_master
cust_master['prob_matrix'] = cust_master['transition_matrix'].apply(matrix_transform)
cust_master.head() 

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


customer                                  transition_matrix  \
0        1  b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
1        2  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
2        3  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
3        4  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
4        5  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   

                                         prob_matrix  
0  b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...  
1  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  
2  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  
3  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...  
4  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...

In [846]:
txn_df = newdf[newdf.txn_break!=0]
txn_df['phone'] = txn_df.phone.astype('str')
txn_df['date'] = pd.to_datetime(txn_df['date']).dt.date

#txn_df = txn_df.head(13)
act_list = ['SMS', 'email', 'App', 'WEB' ]
for i in range(0,len(act_list)):
        cust_master[str(act_list[i])+'_rem_effect'] = 0
cust_master['txn_prob'] = 0

from_axis = {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 , 'start' : 4}
to_axis = {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 , 'Txn' : 4}

for index,row in cust_master.iterrows():
    temp_df = txn_df[txn_df.phone == row['customer']]
    #temp_df = temp_df.sort_values(by = ['phone','date'])
    temp_df.sort_values(by = ['phone','date'], inplace=True)
    
    total_prob = '0'
    start = 1
    
    trans_mat = np.fromstring(row['prob_matrix'],float).reshape(5,6)
    #print(trans_mat)
    temp_df.sort_values(by = ['phone','date'], inplace=True)
    #print(temp_df.sort_values(by = ['phone','date'], inplace=True))
    #print(temp_df)
    for i in range(0,temp_df.shape[0]-1):
        #print(temp_df)
        #print(temp_df.iloc[i,:])
        #print(temp_df.iloc[i,3]+temp_df.iloc[i+1,3])
        if(temp_df.iloc[i,3] == 'Txn'):
            start = 1
            continue
        if(start == 1):
            if(temp_df.iloc[i,3] == 'Txn'):
                continue
            else:
                total_prob = total_prob + '+' +str(trans_mat[4][to_axis[temp_df.iloc[i,3]]])+'*'+str(trans_mat[from_axis[temp_df.iloc[i,3]]][to_axis[temp_df.iloc[i+1,3]]])  
                start = 0
                continue
        total_prob = total_prob +'*'+str(trans_mat[from_axis[temp_df.iloc[i,3]]][to_axis[temp_df.iloc[i+1,3]]])  
    txn_prob = eval(total_prob)
    rem_effect = []
    
    for ac in act_list:
        rem_df = temp_df[~temp_df.txn_id.isin(temp_df[temp_df.act == str(ac)]['txn_id'].unique())]
        start = 1
        rem_prob = '0'
        rem_df.sort_values(by = ['phone','date'],ascending = (True,True),inplace = True)
        for i in range(0,rem_df.shape[0]-1):
            if(rem_df.iloc[i,3] == 'Txn'):
                start = 1
                continue
            if(start == 1):
                if(rem_df.iloc[i,3] == 'Txn'):
                    continue
                else:
                    rem_prob = rem_prob + '+' +str(trans_mat[4][to_axis[rem_df.iloc[i,3]]])+'*'+str(trans_mat[from_axis[rem_df.iloc[i,3]]][to_axis[rem_df.iloc[i+1,3]]])  
                    start = 0
                    continue
            #print(i)
            #print()
            #print(to_axis[rem_df.iloc[i+1,3]])
            
            rem_prob = rem_prob +'*'+str(trans_mat[from_axis[rem_df.iloc[i,3]]][to_axis[rem_df.iloc[i+1,3]]])  
        txn_rem_prob = eval(rem_prob)
        rem_effect.append(txn_rem_prob)
        #rem_df.info()
        #print(rem_df)
        del rem_df
        del rem_prob
    del temp_df
    del total_prob
    for i in range(0,len(act_list)):
        cust_master.loc[index,str(act_list[i])+'_rem_effect'] = rem_effect[i]
    cust_master.loc[index,'txn_prob'] = txn_prob
## Do the 1-total_prob or act/total_prob after confimation 

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stabl

In [847]:
#row['customer']
#txn_df.phone
txn_df.head(13)

phone        date    id    act      txn_dt  txn_id  date_diff  txn_break  \
0      1  2019-01-09  3819    Txn  2019-01-09  3819.0          0          2   
1      1  2019-01-20  4103    App  2019-01-29  3359.0          9          1   
2      1  2019-01-29  3359    Txn  2019-01-29  3359.0          0          2   
5      1  2019-03-21  1592    Txn  2019-03-21  1592.0          0          2   
9      1  2019-05-26  3988    App  2019-06-08  2117.0         13          1   
10     1  2019-05-26   767    SMS  2019-06-08  2117.0         13          1   
11     1  2019-06-08  2117    Txn  2019-06-08  2117.0          0          2   
12     1  2019-06-11  1678    Txn  2019-06-11  1678.0          0          2   
17     1  2019-11-01  2751    Txn  2019-11-01  2751.0          0          2   
27     2  2019-02-28  1378    Txn  2019-02-28  1378.0          0          2   
34     2  2019-06-22  1193  email  2019-06-23  3127.0          1          1   
35     2  2019-06-23  3127    Txn  2019-06-23  3127.0          0          2   
40     2  2019-08-18  2638    Txn  2019-08-18  2638.0          0          2   

    ntp_break  
0           0  
1           0  
2           0  
5           0  
9           0  
10          0  
11          0  
12          0  
17          0  
27          0  
34          0  
35          0  
40          0

In [848]:
cust_master

customer                                  transition_matrix  \
0          1  b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
1          2  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
2          3  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
3          4  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
4          5  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
..       ...                                                ...   
995      996  b'\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x0...   
996      997  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
997      998  b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
998      999  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...   
999     1000  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   

                                           prob_matrix  SMS_rem_effect  \
0    b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
1    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...        0.146684   
2    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...        0.000000   
3    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...        0.080000   
4    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...        0.071429   
..                                                 ...             ...   
995  b'\x00\x00\x00\x00\x00\x00\xd8?\x00\x00\x00\x0...        0.208333   
996  b'\x00\x00\x00\x00\x00\x00\x00\x00UUUUUU\xc5?\...        0.027778   
997  b'\x00\x00\x00\x00\x00\x00\xc0?\x00\x00\x00\x0...        0.111111   
998  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...        0.046154   
999  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   

     email_rem_effect  App_rem_effect  WEB_rem_effect  txn_prob  
0            0.057692        0.000000        0.057692  0.057692  
1            0.021684        0.160714        0.164541  0.164541  
2            0.029412        0.029412        0.029412  0.029412  
3            0.120000        0.040000        0.120000  0.120000  
4            0.000000        0.071429        0.071429  0.071429  
..                ...             ...             ...       ...  
995          0.208333        0.208333        0.000000  0.208333  
996          0.111111        0.138889        0.144676  0.144676  
997          0.111111        0.055556        0.055556  0.111111  
998          0.030769        0.076923        0.076923  0.076923  
999          0.002500        0.125000        0.127500  0.127500  

[1000 rows x 8 columns]

In [851]:
temp_x = pd.DataFrame(txn_df.txn_id.unique())
temp_x['sales'] = np.random.choice(range(1,150),3170)
#act_id = np.random.choice(range(1,5001),5000)
#temp_x.columns
txn_df = txn_df.merge(temp_x,left_on = 'txn_id',right_on = 0,how='left')
del txn_df[0]
#txn_df.head(13)
txn_df = txn_df.merge(cust_master,left_on = 'phone',right_on = 'customer',how='left')
txn_df.head(50)

phone        date    id    act      txn_dt  txn_id  date_diff  txn_break  \
0      1  2019-01-09  3819    Txn  2019-01-09  3819.0          0          2   
1      1  2019-01-20  4103    App  2019-01-29  3359.0          9          1   
2      1  2019-01-29  3359    Txn  2019-01-29  3359.0          0          2   
3      1  2019-03-21  1592    Txn  2019-03-21  1592.0          0          2   
4      1  2019-05-26  3988    App  2019-06-08  2117.0         13          1   
5      1  2019-05-26   767    SMS  2019-06-08  2117.0         13          1   
6      1  2019-06-08  2117    Txn  2019-06-08  2117.0          0          2   
7      1  2019-06-11  1678    Txn  2019-06-11  1678.0          0          2   
8      1  2019-11-01  2751    Txn  2019-11-01  2751.0          0          2   
9      2  2019-02-28  1378    Txn  2019-02-28  1378.0          0          2   
10     2  2019-06-22  1193  email  2019-06-23  3127.0          1          1   
11     2  2019-06-23  3127    Txn  2019-06-23  3127.0          0          2   
12     2  2019-08-18  2638    Txn  2019-08-18  2638.0          0          2   
13     2  2019-10-01  1638    App  2019-10-07  4360.0          6          1   
14     2  2019-10-01  4914    App  2019-10-07  4360.0          6          1   
15     2  2019-10-07  4360    Txn  2019-10-07  4360.0          0          2   
16     2  2019-10-19  1730    SMS  2019-10-27  3237.0          8          1   
17     2  2019-10-27  3237    Txn  2019-10-27  3237.0          0          2   
18     2  2019-11-06    26    Txn  2019-11-06    26.0          0          2   
19     2  2019-12-12  3691  email  2019-12-18   742.0          6          1   
20     2  2019-12-18   742    Txn  2019-12-18   742.0          0          2   
21     3  2019-03-02  3139    Txn  2019-03-02  3139.0          0          2   
22     3  2019-03-08  2907    Txn  2019-03-08  2907.0          0          2   
23     3  2019-03-15  2869    Txn  2019-03-15  2869.0          0          2   
24     3  2019-06-08  1343    SMS  2019-06-11   337.0          3          1   
25     3  2019-06-11   337    Txn  2019-06-11   337.0          0          2   
26     3  2019-07-09   196    Txn  2019-07-09   196.0          0          2   
27     3  2019-08-19  1741    Txn  2019-08-19  1741.0          0          2   
28     4  2019-01-03  1039    Txn  2019-01-03  1039.0          0          2   
29     4  2019-01-09  3942    Txn  2019-01-09  3942.0          0          2   
30     4  2019-02-21  3363    SMS  2019-03-05   383.0         12          1   
31     4  2019-03-05   383    Txn  2019-03-05   383.0          0          2   
32     4  2019-05-04   627    App  2019-05-16  1433.0         12          1   
33     4  2019-05-16  1433    Txn  2019-05-16  1433.0          0          2   
34     4  2019-10-13   952    Txn  2019-10-13   952.0          0          2   
35     5  2019-01-02  1796    Txn  2019-01-02  1796.0          0          2   
36     5  2019-07-02   382    Txn  2019-07-02   382.0          0          2   
37     5  2019-08-15  4484    Txn  2019-08-15  4484.0          0          2   
38     5  2019-09-09   100  email  2019-09-13   627.0          4          1   
39     5  2019-09-13   627    Txn  2019-09-13   627.0          0          2   
40     5  2019-10-25   553    Txn  2019-10-25   553.0          0          2   
41     6  2019-04-15  4045    WEB  2019-04-23  3491.0          8          1   
42     6  2019-04-23  3491    Txn  2019-04-23  3491.0          0          2   
43     6  2019-10-06  1844    Txn  2019-10-06  1844.0          0          2   
44     6  2019-10-27  1167    Txn  2019-10-27  1167.0          0          2   
45     7  2019-02-21   177    App  2019-03-02   960.0          9          1   
46     7  2019-03-02   960    Txn  2019-03-02   960.0          0          2   
47     7  2019-06-09  4076    App  2019-06-16   565.0          7          1   
48     7  2019-06-14   286  email  2019-06-16   565.0          2          1   
49     7  2019-06-16   565    Txn  2019-06-16   565.0

In [873]:
act_matrix = [0,0,0,0]
act_idx =  {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 }
#np.fromstring(txn_df.loc[0,'prob_matrix'],float).reshape(5,6)[4][act_idx[txn_df.loc[i,'act']]]
0/0


ZeroDivisionError: division by zero

In [881]:
def zero_div(n, d):
    return n / d if d else 0

dtypes = np.dtype([
          ('Transaction', int),
          ('date', object),
          ('sale_val', object),
          ('units', object),
          ('SMS', float),
          ('email', float),
          ('App', float),
          ('WEB', float),
          ])
data = np.empty(0, dtype=dtypes)
transaction_breakdown = pd.DataFrame(data)

#SMS_rem_effect    -    13
#email_rem_effect    -    14
#App_rem_effect    -    15
#WEB_rem_effect    -    16
#txn_prob    -    17

act_dict = {'SMS': 13, 'email': 14, 'App': 15, 'WEB':16 }
act_idx =  {'SMS': 0, 'email': 1, 'App': 2, 'WEB':3 }

curr_txn = txn_df.loc[0,'txn_id']
act_matrix=[0,0,0,0]
curr_txn_id = txn_df.loc[0,'txn_id']
curr_txn_date = txn_df.loc[0,'date']
curr_sale = txn_df.loc[0,'sales']
curr_units = 0

start  = 1
for i in range(0,txn_df.shape[0]):
    if(txn_df.loc[i,'txn_id'] != curr_txn_id):
        
        row = [str(curr_txn_id), curr_txn_date,curr_sale,curr_units,curr_sale*zero_div(act_matrix[0],sum(act_matrix)),curr_sale*zero_div(act_matrix[1],sum(act_matrix)),curr_sale*zero_div(act_matrix[2],sum(act_matrix)),curr_sale*zero_div(act_matrix[3],sum(act_matrix))]   
        transaction_breakdown.loc[len(transaction_breakdown)] = row
                
        curr_txn_id = txn_df.loc[i,'txn_id']
        curr_txn_date = txn_df.loc[i,'date']
        curr_sale = txn_df.loc[i,'sales']
        curr_units = 0
        act_matrix=[0,0,0,0]
        start = 1
    if(txn_df.loc[i,'act'] == 'Txn'):
        continue
    else:
        act_matrix[act_idx[txn_df.loc[i,'act']]] = act_matrix[act_idx[txn_df.loc[i,'act']]] + ((15-int(txn_df.loc[i,'date_diff'])) * (1+float(txn_df.iloc[i,act_dict[txn_df.loc[i,'act']]])))      
            
        
        

In [879]:
transaction_breakdown.head()

Transaction        date sale_val units       SMS  email        App  WEB
0      3819.0  2019-01-09       72     0  0.000000    0.0   0.000000  0.0
1      3359.0          84       84    84  0.000000    0.0  84.000000  0.0
2      1592.0          94       94    94  0.000000    0.0   0.000000  0.0
3      2117.0           3        3     3  1.528302    0.0   1.471698  0.0
4      1678.0         120      120   120  0.000000    0.0   0.000000  0.0

In [882]:
txn_df.head(50)

phone        date    id    act      txn_dt  txn_id  date_diff  txn_break  \
0      1  2019-01-09  3819    Txn  2019-01-09  3819.0          0          2   
1      1  2019-01-20  4103    App  2019-01-29  3359.0          9          1   
2      1  2019-01-29  3359    Txn  2019-01-29  3359.0          0          2   
3      1  2019-03-21  1592    Txn  2019-03-21  1592.0          0          2   
4      1  2019-05-26  3988    App  2019-06-08  2117.0         13          1   
5      1  2019-05-26   767    SMS  2019-06-08  2117.0         13          1   
6      1  2019-06-08  2117    Txn  2019-06-08  2117.0          0          2   
7      1  2019-06-11  1678    Txn  2019-06-11  1678.0          0          2   
8      1  2019-11-01  2751    Txn  2019-11-01  2751.0          0          2   
9      2  2019-02-28  1378    Txn  2019-02-28  1378.0          0          2   
10     2  2019-06-22  1193  email  2019-06-23  3127.0          1          1   
11     2  2019-06-23  3127    Txn  2019-06-23  3127.0          0          2   
12     2  2019-08-18  2638    Txn  2019-08-18  2638.0          0          2   
13     2  2019-10-01  1638    App  2019-10-07  4360.0          6          1   
14     2  2019-10-01  4914    App  2019-10-07  4360.0          6          1   
15     2  2019-10-07  4360    Txn  2019-10-07  4360.0          0          2   
16     2  2019-10-19  1730    SMS  2019-10-27  3237.0          8          1   
17     2  2019-10-27  3237    Txn  2019-10-27  3237.0          0          2   
18     2  2019-11-06    26    Txn  2019-11-06    26.0          0          2   
19     2  2019-12-12  3691  email  2019-12-18   742.0          6          1   
20     2  2019-12-18   742    Txn  2019-12-18   742.0          0          2   
21     3  2019-03-02  3139    Txn  2019-03-02  3139.0          0          2   
22     3  2019-03-08  2907    Txn  2019-03-08  2907.0          0          2   
23     3  2019-03-15  2869    Txn  2019-03-15  2869.0          0          2   
24     3  2019-06-08  1343    SMS  2019-06-11   337.0          3          1   
25     3  2019-06-11   337    Txn  2019-06-11   337.0          0          2   
26     3  2019-07-09   196    Txn  2019-07-09   196.0          0          2   
27     3  2019-08-19  1741    Txn  2019-08-19  1741.0          0          2   
28     4  2019-01-03  1039    Txn  2019-01-03  1039.0          0          2   
29     4  2019-01-09  3942    Txn  2019-01-09  3942.0          0          2   
30     4  2019-02-21  3363    SMS  2019-03-05   383.0         12          1   
31     4  2019-03-05   383    Txn  2019-03-05   383.0          0          2   
32     4  2019-05-04   627    App  2019-05-16  1433.0         12          1   
33     4  2019-05-16  1433    Txn  2019-05-16  1433.0          0          2   
34     4  2019-10-13   952    Txn  2019-10-13   952.0          0          2   
35     5  2019-01-02  1796    Txn  2019-01-02  1796.0          0          2   
36     5  2019-07-02   382    Txn  2019-07-02   382.0          0          2   
37     5  2019-08-15  4484    Txn  2019-08-15  4484.0          0          2   
38     5  2019-09-09   100  email  2019-09-13   627.0          4          1   
39     5  2019-09-13   627    Txn  2019-09-13   627.0          0          2   
40     5  2019-10-25   553    Txn  2019-10-25   553.0          0          2   
41     6  2019-04-15  4045    WEB  2019-04-23  3491.0          8          1   
42     6  2019-04-23  3491    Txn  2019-04-23  3491.0          0          2   
43     6  2019-10-06  1844    Txn  2019-10-06  1844.0          0          2   
44     6  2019-10-27  1167    Txn  2019-10-27  1167.0          0          2   
45     7  2019-02-21   177    App  2019-03-02   960.0          9          1   
46     7  2019-03-02   960    Txn  2019-03-02   960.0          0          2   
47     7  2019-06-09  4076    App  2019-06-16   565.0          7          1   
48     7  2019-06-14   286  email  2019-06-16   565.0          2          1   
49     7  2019-06-16   565    Txn  2019-06-16   565.0

In [857]:
float('4.5')

4.5

In [854]:
for c in txn_df.columns:
    print(c + '    -    ' + str(txn_df.columns.get_loc(c)))

phone    -    0
date    -    1
id    -    2
act    -    3
txn_dt    -    4
txn_id    -    5
date_diff    -    6
txn_break    -    7
ntp_break    -    8
sales    -    9
customer    -    10
transition_matrix    -    11
prob_matrix    -    12
SMS_rem_effect    -    13
email_rem_effect    -    14
App_rem_effect    -    15
WEB_rem_effect    -    16
txn_prob    -    17


In [852]:
txn_df

phone        date    id    act      txn_dt  txn_id  date_diff  txn_break  \
0        1  2019-01-09  3819    Txn  2019-01-09  3819.0          0          2   
1        1  2019-01-20  4103    App  2019-01-29  3359.0          9          1   
2        1  2019-01-29  3359    Txn  2019-01-29  3359.0          0          2   
3        1  2019-03-21  1592    Txn  2019-03-21  1592.0          0          2   
4        1  2019-05-26  3988    App  2019-06-08  2117.0         13          1   
...    ...         ...   ...    ...         ...     ...        ...        ...   
8467  1000  2019-06-09  3846  email  2019-06-10  1026.0          1          1   
8468  1000  2019-06-10  1026    Txn  2019-06-10  1026.0          0          2   
8469  1000  2019-07-29  4293    Txn  2019-07-29  4293.0          0          2   
8470  1000  2019-08-10  2955    Txn  2019-08-10  2955.0          0          2   
8471  1000  2019-10-19  1518    Txn  2019-10-19  1518.0          0          2   

      ntp_break  sales customer  \
0             0     72        1   
1             0     84        1   
2             0     84        1   
3             0     94        1   
4             0      3        1   
...         ...    ...      ...   
8467          0    113     1000   
8468          0    113     1000   
8469          0     37     1000   
8470          0     40     1000   
8471          0    113     1000   

                                      transition_matrix  \
0     b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
1     b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
2     b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
3     b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
4     b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x0...   
...                                                 ...   
8467  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   
8468  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   
8469  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   
8470  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   
8471  b'\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x0...   

                                            prob_matrix  SMS_rem_effect  \
0     b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
1     b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
2     b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
3     b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
4     b'\x00\x00\x00\x00\x00\x00\xd0?\x00\x00\x00\x0...        0.038462   
...                                                 ...             ...   
8467  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   
8468  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   
8469  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   
8470  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   
8471  b'\x9a\x99\x99\x99\x99\x99\xc9?\x1c\xc7q\x1c\x...        0.127500   

      email_rem_effect  App_rem_effect  WEB_rem_effect  txn_prob  
0             0.057692           0.000        0.057692  0.057692  
1             0.057692           0.000        0.057692  0.057692  
2             0.057692           0.000        0.057692  0.057692  
3             0.057692           0.000        0.057692  0.057692  
4             0.057692           0.000        0.057692  0.057692  
...                ...             ...             ...       ...  
8467          0.002500           0.125        0.127500  0.127500  
8468          0.002500           0.125        0.127500  0.127500  
8469          0.002500           0.125        0.127500  0.127500  
8470          0.002500           0.125        0.127500  0.127500  
8471          0.002500           0.125        0.127500  0.127500  

[8472 rows x 18 columns]

In [614]:
#np.fromstring(a.tostring(),int)
#np.fromstring(p.tostring(),float)
#np.fromstring(conv_act.tostring(),float).reshape(5,6)
newdf[~newdf.txn_id.isin(newdf[newdf.act == 'App']['txn_id'].unique())]

phone        date    id    act      txn_dt  txn_id  date_diff  \
38         2  2019-07-06   233    Txn  2019-07-06   233.0          0   
84         3  2019-11-29  3765    Txn  2019-11-29  3765.0          0   
103        4  2019-06-20  1079    SMS  2019-06-20  1022.0          0   
104        4  2019-07-09  4199    SMS  2019-07-17  1022.0          8   
105        4  2019-07-17  1022    Txn  2019-07-17  1022.0          0   
...      ...         ...   ...    ...         ...     ...        ...   
24954    998  2019-10-17  1087    Txn  2019-10-17  1087.0          0   
24956    999  2019-01-04  3041    Txn  2019-01-04  3041.0          0   
24960    999  2019-01-31  1056  email  2019-01-31  2757.0          0   
24961    999  2019-02-16  2757    Txn  2019-02-16  2757.0          0   
24965    999  2019-04-11  1808    Txn  2019-04-11  1808.0          0   

       txn_break  ntp_break  
38             2          0  
84             2          0  
103            0          1  
104            1          0  
105            2          0  
...          ...        ...  
24954          2          0  
24956          2          0  
24960          0          1  
24961          2          0  
24965          2          0  

[4266 rows x 9 columns]

In [466]:
np.fromstring(cust_master.iloc[5,1]).reshape(5,6)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([[3., 0., 1., 1., 1., 4.],
       [1., 1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 0., 4.],
       [1., 0., 1., 0., 0., 3.],
       [4., 3., 4., 3., 3., 0.]])

In [405]:
#from datetime import datetime
#date_format = "%Y-%m-%d"
#(pd.to_datetime('1970-01-01') - pd.to_datetime(newdf.iloc[10,4])).days
#newdf.date.max()

#a = datetime.strptime(break_dt, date_format)
#b = datetime.strptime(newdf.iloc[i,4], date_format)
#(a-b).days >15
#pd.to_datetime(pd.to_datetime(break_dt) - pd.to_datetime(newdf.iloc[i,4])).days > 15

In [479]:
#for c in newdf.columns:
#    print(c + '    -    ' + str(newdf.columns.get_loc(c)))
y

array([0.66666667, 0.71428571, 0.44444444, 0.4       , 0.66666667,
       0.        ])

In [488]:
# calculating removal effect
x = conv_act.copy()
y = x[-1].copy()
#x[4]/x[4].sum()
#x[:,0] = x[:,0]/x[:,0].sum()
#x=x.astype(int)
for i in range(0,x.shape[1]):
    x[:,i] = x[:,i]/(x[:,i].sum())
x[-1] = y/y.sum()
pd.DataFrame(x)

0         1         2         3         4         5
0  0.000000  0.000000  0.111111  0.000000  0.000000  0.181818
1  0.000000  0.000000  0.111111  0.200000  0.333333  0.272727
2  0.000000  0.285714  0.111111  0.200000  0.000000  0.454545
3  0.333333  0.000000  0.222222  0.200000  0.000000  0.090909
4  0.117647  0.294118  0.235294  0.117647  0.235294  0.000000

In [487]:
conv_act

array([[0., 0., 1., 0., 0., 2.],
       [0., 0., 1., 1., 2., 3.],
       [0., 2., 1., 1., 0., 5.],
       [1., 0., 2., 1., 0., 1.],
       [2., 5., 4., 2., 4., 0.]])

In [478]:
for i in range(0,x.shape[1]):
    x[:,i] = x[:,i]/(x[:,i].sum())
x

array([[0.        , 0.        , 0.11111111, 0.        , 0.        ,
        0.18181818],
       [0.        , 0.        , 0.11111111, 0.2       , 0.33333333,
        0.27272727],
       [0.        , 0.28571429, 0.11111111, 0.2       , 0.        ,
        0.45454545],
       [0.33333333, 0.        , 0.22222222, 0.2       , 0.        ,
        0.09090909],
       [0.66666667, 0.71428571, 0.44444444, 0.4       , 0.66666667,
        0.        ]])

In [553]:
cust_master.shape

(24977, 2)

## V1 for column level operations 

In [355]:
fdf['sms_lag_0'] = 0
fdf['sms_lag_1'] = 0
fdf['sms_lag_2'] = 0
fdf['sms_lag_3'] = 0
fdf['sms_lag_4'] = 0
fdf['sms_lag_5'] = 0
fdf['sms_lag_6'] = 0
fdf['sms_lag_7'] = 0
fdf['sms_lag_8'] = 0
fdf['sms_lag_9'] = 0
fdf['sms_lag_10'] = 0
fdf['sms_lag_11'] = 0
fdf['sms_lag_12'] = 0
fdf['sms_lag_13'] = 0

fdf['web_lag_0'] = 0
fdf['web_lag_1'] = 0
fdf['web_lag_2'] = 0
fdf['web_lag_3'] = 0
fdf['web_lag_4'] = 0
fdf['web_lag_5'] = 0
fdf['web_lag_6'] = 0
fdf['web_lag_7'] = 0
fdf['web_lag_8'] = 0
fdf['web_lag_9'] = 0
fdf['web_lag_10'] = 0
fdf['web_lag_11'] = 0
fdf['web_lag_12'] = 0
fdf['web_lag_13'] = 0

fdf['email_lag_0'] = 0
fdf['email_lag_1'] = 0
fdf['email_lag_2'] = 0
fdf['email_lag_3'] = 0
fdf['email_lag_4'] = 0
fdf['email_lag_5'] = 0
fdf['email_lag_6'] = 0
fdf['email_lag_7'] = 0
fdf['email_lag_8'] = 0
fdf['email_lag_9'] = 0
fdf['email_lag_10'] = 0
fdf['email_lag_11'] = 0
fdf['email_lag_12'] = 0
fdf['email_lag_13'] = 0

fdf['app_lag_0'] = 0
fdf['app_lag_1'] = 0
fdf['app_lag_2'] = 0
fdf['app_lag_3'] = 0
fdf['app_lag_4'] = 0
fdf['app_lag_5'] = 0
fdf['app_lag_6'] = 0
fdf['app_lag_7'] = 0
fdf['app_lag_8'] = 0
fdf['app_lag_9'] = 0
fdf['app_lag_10'] = 0
fdf['app_lag_11'] = 0
fdf['app_lag_12'] = 0
fdf['app_lag_13'] = 0

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pyda

In [356]:
fdf

phone        date    id    act      txn_dt  txn_id  date_diff  \
5          1  2019-04-20  4721  email  2019-04-26  1233.0        6.0   
6          1  2019-04-28  3032    App  2019-05-09  2975.0       11.0   
7          1  2019-05-06  4758    App  2019-05-09  2975.0        3.0   
8          1  2019-05-08   738  email  2019-05-09  2975.0        1.0   
11         1  2019-06-07  2555  email  2019-06-16  2642.0        9.0   
...      ...         ...   ...    ...         ...     ...        ...   
19976   1000  2019-01-04   337  email  2019-01-12  3879.0        8.0   
19977   1000  2019-01-20   505  email  2019-01-24   241.0        4.0   
19978   1000  2019-01-24  4809    App  2019-01-24   241.0        0.0   
19998   1000  2019-12-28  1556    App  2019-12-29  4326.0        1.0   
19999   1000  2019-12-29  2742    SMS  2019-12-29  4326.0        0.0   

       sms_lag_0  sms_lag_1  sms_lag_2  ...  app_lag_4  app_lag_5  app_lag_6  \
5              0          0          0  ...          0          0          0   
6              0          0          0  ...          0          0          0   
7              0          0          0  ...          0          0          0   
8              0          0          0  ...          0          0          0   
11             0          0          0  ...          0          0          0   
...          ...        ...        ...  ...        ...        ...        ...   
19976          0          0          0  ...          0          0          0   
19977          0          0          0  ...          0          0          0   
19978          0          0          0  ...          0          0          0   
19998          0          0          0  ...          0          0          0   
19999          0          0          0  ...          0          0          0   

       app_lag_7  app_lag_8  app_lag_9  app_lag_10  app_lag_11  app_lag_12  \
5              0          0          0           0           0           0   
6              0          0          0           0           0           0   
7              0          0          0           0           0           0   
8              0          0          0           0           0           0   
11             0          0          0           0           0           0   
...          ...        ...        ...         ...         ...         ...   
19976          0          0          0           0           0           0   
19977          0          0          0           0           0           0   
19978          0          0          0           0           0           0   
19998          0          0          0           0           0           0   
19999          0          0          0           0           0           0   

       app_lag_13  
5               0  
6               0  
7               0  
8               0  
11              0  
...           ...  
19976           0  
19977           0  
19978           0  
19998           0  
19999           0  

[3421 rows x 63 columns]

In [357]:
fdf.loc[(fdf.date_diff == 0) & (fdf.act=='WEB'),'web_lag_0'] 

118      0
203      0
243      0
626      0
742      0
        ..
18240    0
18998    0
19750    0
19844    0
19849    0
Name: web_lag_0, Length: 65, dtype: int64

In [358]:
fdf.loc[(fdf.date_diff == 0) & (fdf.act=='SMS'),'sms_lag_0'] = 1
fdf.loc[(fdf.date_diff == 1) & (fdf.act=='SMS'),'sms_lag_1'] = 1
fdf.loc[(fdf.date_diff == 2) & (fdf.act=='SMS'),'sms_lag_2'] = 1
fdf.loc[(fdf.date_diff == 3) & (fdf.act=='SMS'),'sms_lag_3'] = 1
fdf.loc[(fdf.date_diff == 4) & (fdf.act=='SMS'),'sms_lag_4'] = 1
fdf.loc[(fdf.date_diff == 5) & (fdf.act=='SMS'),'sms_lag_5'] = 1
fdf.loc[(fdf.date_diff == 6) & (fdf.act=='SMS'),'sms_lag_6'] = 1
fdf.loc[(fdf.date_diff == 7) & (fdf.act=='SMS'),'sms_lag_7'] = 1
fdf.loc[(fdf.date_diff == 8) & (fdf.act=='SMS'),'sms_lag_8'] = 1
fdf.loc[(fdf.date_diff == 9) & (fdf.act=='SMS'),'sms_lag_9'] = 1
fdf.loc[(fdf.date_diff == 10) & (fdf.act=='SMS'),'sms_lag_10'] = 1
fdf.loc[(fdf.date_diff == 11) & (fdf.act=='SMS'),'sms_lag_11'] = 1
fdf.loc[(fdf.date_diff == 12) & (fdf.act=='SMS'),'sms_lag_12'] = 1
fdf.loc[(fdf.date_diff == 13) & (fdf.act=='SMS'),'sms_lag_13'] = 1

fdf.loc[(fdf.date_diff == 0) & (fdf.act=='WEB'),'web_lag_0'] = 1
fdf.loc[(fdf.date_diff == 1) & (fdf.act=='WEB'),'web_lag_1'] = 1
fdf.loc[(fdf.date_diff == 2) & (fdf.act=='WEB'),'web_lag_2'] = 1
fdf.loc[(fdf.date_diff == 3) & (fdf.act=='WEB'),'web_lag_3'] = 1
fdf.loc[(fdf.date_diff == 4) & (fdf.act=='WEB'),'web_lag_4'] = 1
fdf.loc[(fdf.date_diff == 5) & (fdf.act=='WEB'),'web_lag_5'] = 1
fdf.loc[(fdf.date_diff == 6) & (fdf.act=='WEB'),'web_lag_6'] = 1
fdf.loc[(fdf.date_diff == 7) & (fdf.act=='WEB'),'web_lag_7'] = 1
fdf.loc[(fdf.date_diff == 8) & (fdf.act=='WEB'),'web_lag_8'] = 1
fdf.loc[(fdf.date_diff == 9) & (fdf.act=='WEB'),'web_lag_9'] = 1
fdf.loc[(fdf.date_diff == 10) & (fdf.act=='WEB'),'web_lag_10'] = 1
fdf.loc[(fdf.date_diff == 11) & (fdf.act=='WEB'),'web_lag_11'] = 1
fdf.loc[(fdf.date_diff == 12) & (fdf.act=='WEB'),'web_lag_12'] = 1
fdf.loc[(fdf.date_diff == 13) & (fdf.act=='WEB'),'web_lag_13'] = 1

fdf.loc[(fdf.date_diff == 0) & (fdf.act=='email'),'email_lag_0'] = 1
fdf.loc[(fdf.date_diff == 1) & (fdf.act=='email'),'email_lag_1'] = 1
fdf.loc[(fdf.date_diff == 2) & (fdf.act=='email'),'email_lag_2'] = 1
fdf.loc[(fdf.date_diff == 3) & (fdf.act=='email'),'email_lag_3'] = 1
fdf.loc[(fdf.date_diff == 4) & (fdf.act=='email'),'email_lag_4'] = 1
fdf.loc[(fdf.date_diff == 5) & (fdf.act=='email'),'email_lag_5'] = 1
fdf.loc[(fdf.date_diff == 6) & (fdf.act=='email'),'email_lag_6'] = 1
fdf.loc[(fdf.date_diff == 7) & (fdf.act=='email'),'email_lag_7'] = 1
fdf.loc[(fdf.date_diff == 8) & (fdf.act=='email'),'email_lag_8'] = 1
fdf.loc[(fdf.date_diff == 9) & (fdf.act=='email'),'email_lag_9'] = 1
fdf.loc[(fdf.date_diff == 10) & (fdf.act=='email'),'email_lag_10'] = 1
fdf.loc[(fdf.date_diff == 11) & (fdf.act=='email'),'email_lag_11'] = 1
fdf.loc[(fdf.date_diff == 12) & (fdf.act=='email'),'email_lag_12'] = 1
fdf.loc[(fdf.date_diff == 13) & (fdf.act=='email'),'email_lag_13'] = 1


fdf.loc[(fdf.date_diff == 0) & (fdf.act=='App'),'app_lag_0'] = 1
fdf.loc[(fdf.date_diff == 1) & (fdf.act=='App'),'app_lag_1'] = 1
fdf.loc[(fdf.date_diff == 2) & (fdf.act=='App'),'app_lag_2'] = 1
fdf.loc[(fdf.date_diff == 3) & (fdf.act=='App'),'app_lag_3'] = 1
fdf.loc[(fdf.date_diff == 4) & (fdf.act=='App'),'app_lag_4'] = 1
fdf.loc[(fdf.date_diff == 5) & (fdf.act=='App'),'app_lag_5'] = 1
fdf.loc[(fdf.date_diff == 6) & (fdf.act=='App'),'app_lag_6'] = 1
fdf.loc[(fdf.date_diff == 7) & (fdf.act=='App'),'app_lag_7'] = 1
fdf.loc[(fdf.date_diff == 8) & (fdf.act=='App'),'app_lag_8'] = 1
fdf.loc[(fdf.date_diff == 9) & (fdf.act=='App'),'app_lag_9'] = 1
fdf.loc[(fdf.date_diff == 10) & (fdf.act=='App'),'app_lag_10'] = 1
fdf.loc[(fdf.date_diff == 11) & (fdf.act=='App'),'app_lag_11'] = 1
fdf.loc[(fdf.date_diff == 12) & (fdf.act=='App'),'app_lag_12'] = 1
fdf.loc[(fdf.date_diff == 13) & (fdf.act=='App'),'app_lag_13'] = 1


C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [377]:
import multiprocessing
multiprocessing.cpu_count()

4

In [359]:
stage = fdf.groupby(['phone','txn_id','txn_dt'])[['sms_lag_1', 'sms_lag_0', 'sms_lag_2', 'sms_lag_3', 'sms_lag_4',
       'sms_lag_5', 'sms_lag_6', 'sms_lag_7', 'sms_lag_8', 'sms_lag_9',
       'sms_lag_10', 'sms_lag_11', 'sms_lag_12', 'sms_lag_13', 'web_lag_0',
       'web_lag_1', 'web_lag_2', 'web_lag_3', 'web_lag_4', 'web_lag_5',
       'web_lag_6', 'web_lag_7', 'web_lag_8', 'web_lag_9', 'web_lag_10',
       'web_lag_11', 'web_lag_12', 'web_lag_13', 'email_lag_0', 'email_lag_1',
       'email_lag_2', 'email_lag_3', 'email_lag_4', 'email_lag_5',
       'email_lag_6', 'email_lag_7', 'email_lag_8', 'email_lag_9',
       'email_lag_10', 'email_lag_11', 'email_lag_12', 'email_lag_13',
       'app_lag_0', 'app_lag_1', 'app_lag_2', 'app_lag_3', 'app_lag_4',
       'app_lag_5', 'app_lag_6', 'app_lag_7', 'app_lag_8', 'app_lag_9',
       'app_lag_10', 'app_lag_11', 'app_lag_12', 'app_lag_13']].agg('sum')
stage = stage.reset_index()

In [360]:
stage.head()

phone  txn_id      txn_dt  sms_lag_1  sms_lag_0  sms_lag_2  sms_lag_3  \
0      1  1233.0  2019-04-26          0          0          0          0   
1      1  2642.0  2019-06-16          0          0          0          1   
2      1  2975.0  2019-05-09          0          0          0          0   
3      2   236.0  2019-10-09          0          0          0          0   
4      2   681.0  2019-10-31          0          0          0          0   

   sms_lag_4  sms_lag_5  sms_lag_6  ...  app_lag_4  app_lag_5  app_lag_6  \
0          0          0          0  ...          0          0          0   
1          0          0          0  ...          0          0          0   
2          0          0          0  ...          0          0          0   
3          1          0          0  ...          0          0          0   
4          0          0          0  ...          1          0          0   

   app_lag_7  app_lag_8  app_lag_9  app_lag_10  app_lag_11  app_lag_12  \
0          0          0          0           0           0           0   
1          0          0          0           0           0           0   
2          0          0          0           0           1           0   
3          0          0          0           0           0           0   
4          0          0          0           0           1           0   

   app_lag_13  
0           0  
1           0  
2           0  
3           0  
4           0  

[5 rows x 59 columns]

In [361]:
import numpy
back_2 = fdf
fdf = stage
base_transitions = numpy.zeros((4, 4))
fdf = fdf[['phone',  'txn_dt', 'txn_id', 
       'sms_lag_0','sms_lag_1', 'sms_lag_2', 'sms_lag_3', 'sms_lag_4',
       'sms_lag_5', 'sms_lag_6', 'sms_lag_7', 'sms_lag_8', 'sms_lag_9',
       'sms_lag_10', 'sms_lag_11', 'sms_lag_12', 'sms_lag_13', 'web_lag_0',
       'web_lag_1', 'web_lag_2', 'web_lag_3', 'web_lag_4', 'web_lag_5',
       'web_lag_6', 'web_lag_7', 'web_lag_8', 'web_lag_9', 'web_lag_10',
       'web_lag_11', 'web_lag_12', 'web_lag_13', 'email_lag_0', 'email_lag_1',
       'email_lag_2', 'email_lag_3', 'email_lag_4', 'email_lag_5',
       'email_lag_6', 'email_lag_7', 'email_lag_8', 'email_lag_9',
       'email_lag_10', 'email_lag_11', 'email_lag_12', 'email_lag_13',
       'app_lag_0', 'app_lag_1', 'app_lag_2', 'app_lag_3', 'app_lag_4',
       'app_lag_5', 'app_lag_6', 'app_lag_7', 'app_lag_8', 'app_lag_9',
       'app_lag_10', 'app_lag_11', 'app_lag_12', 'app_lag_13']]

In [362]:
for c in fdf.columns:
    print(c + '    -    ' + str(fdf.columns.get_loc(c)))
 #fdf.columns.get_loc('')

phone    -    0
txn_dt    -    1
txn_id    -    2
sms_lag_0    -    3
sms_lag_1    -    4
sms_lag_2    -    5
sms_lag_3    -    6
sms_lag_4    -    7
sms_lag_5    -    8
sms_lag_6    -    9
sms_lag_7    -    10
sms_lag_8    -    11
sms_lag_9    -    12
sms_lag_10    -    13
sms_lag_11    -    14
sms_lag_12    -    15
sms_lag_13    -    16
web_lag_0    -    17
web_lag_1    -    18
web_lag_2    -    19
web_lag_3    -    20
web_lag_4    -    21
web_lag_5    -    22
web_lag_6    -    23
web_lag_7    -    24
web_lag_8    -    25
web_lag_9    -    26
web_lag_10    -    27
web_lag_11    -    28
web_lag_12    -    29
web_lag_13    -    30
email_lag_0    -    31
email_lag_1    -    32
email_lag_2    -    33
email_lag_3    -    34
email_lag_4    -    35
email_lag_5    -    36
email_lag_6    -    37
email_lag_7    -    38
email_lag_8    -    39
email_lag_9    -    40
email_lag_10    -    41
email_lag_11    -    42
email_lag_12    -    43
email_lag_13    -    44
app_lag_0    -    45
app_lag_1    -

In [363]:
test_1 = numpy.zeros((1, 4))
test_2 = numpy.zeros((4,1))
print(test_2@test_1)
print(test_1)
#print(test_1.T)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]]


In [364]:
row = fdf
#lag_0 = np.array([row.iloc[1,7],row.iloc[1,21],row.iloc[1,35],row.iloc[1,49]], ndmin = 2)
#lag_0 = [row.iloc[1,7],row.iloc[1,21],row.iloc[1,35],row.iloc[1,49]]
row['temp'] = '[' + row['sms_lag_0'].astype(str) +', ' + row['web_lag_0'].astype(str)  + ', '+ row['email_lag_0'] .astype(str) +', ' + row['app_lag_0'].astype(str)  + ']' 
#lag_0.shape
eval(row.iloc[1,63])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


IndexError: single positional indexer is out-of-bounds

In [365]:
fdf['lag_0']  = '[' + fdf['sms_lag_0'].astype(str) +', ' + fdf['web_lag_0'].astype(str)  + ', '+ fdf['email_lag_0'] .astype(str) +', ' + fdf['app_lag_0'].astype(str)  + ']' 
fdf.drop(['sms_lag_0','web_lag_0','email_lag_0','app_lag_0'], axis = 1 , inplace = True)
fdf['lag_1']  = '[' + fdf['sms_lag_1'].astype(str) +', ' + fdf['web_lag_1'].astype(str)  + ', '+ fdf['email_lag_1'] .astype(str) +', ' + fdf['app_lag_1'].astype(str)  + ']' 
fdf.drop(['sms_lag_1','web_lag_1','email_lag_1','app_lag_1'], axis = 1 , inplace = True)
fdf['lag_2']  = '[' + fdf['sms_lag_2'].astype(str) +', ' + fdf['web_lag_2'].astype(str)  + ', '+ fdf['email_lag_2'] .astype(str) +', ' + fdf['app_lag_2'].astype(str)  + ']' 
fdf.drop(['sms_lag_2','web_lag_2','email_lag_2','app_lag_2'], axis = 1 , inplace = True)
fdf['lag_3']  = '[' + fdf['sms_lag_3'].astype(str) +', ' + fdf['web_lag_3'].astype(str)  + ', '+ fdf['email_lag_3'] .astype(str) +', ' + fdf['app_lag_3'].astype(str)  + ']' 
fdf.drop(['sms_lag_3','web_lag_3','email_lag_3','app_lag_3'], axis = 1 , inplace = True)
fdf['lag_4']  = '[' + fdf['sms_lag_4'].astype(str) +', ' + fdf['web_lag_4'].astype(str)  + ', '+ fdf['email_lag_4'] .astype(str) +', ' + fdf['app_lag_4'].astype(str)  + ']' 
fdf.drop(['sms_lag_4','web_lag_4','email_lag_4','app_lag_4'], axis = 1 , inplace = True)
fdf['lag_5']  = '[' + fdf['sms_lag_5'].astype(str) +', ' + fdf['web_lag_5'].astype(str)  + ', '+ fdf['email_lag_5'] .astype(str) +', ' + fdf['app_lag_5'].astype(str)  + ']' 
fdf.drop(['sms_lag_5','web_lag_5','email_lag_5','app_lag_5'], axis = 1 , inplace = True)
fdf['lag_6']  = '[' + fdf['sms_lag_6'].astype(str) +', ' + fdf['web_lag_6'].astype(str)  + ', '+ fdf['email_lag_6'] .astype(str) +', ' + fdf['app_lag_6'].astype(str)  + ']' 
fdf.drop(['sms_lag_6','web_lag_6','email_lag_6','app_lag_6'], axis = 1 , inplace = True)
fdf['lag_7']  = '[' + fdf['sms_lag_7'].astype(str) +', ' + fdf['web_lag_7'].astype(str)  + ', '+ fdf['email_lag_7'] .astype(str) +', ' + fdf['app_lag_7'].astype(str)  + ']' 
fdf.drop(['sms_lag_7','web_lag_7','email_lag_7','app_lag_7'], axis = 1 , inplace = True)
fdf['lag_8']  = '[' + fdf['sms_lag_8'].astype(str) +', ' + fdf['web_lag_8'].astype(str)  + ', '+ fdf['email_lag_8'] .astype(str) +', ' + fdf['app_lag_8'].astype(str)  + ']' 
fdf.drop(['sms_lag_8','web_lag_8','email_lag_8','app_lag_8'], axis = 1 , inplace = True)
fdf['lag_9']  = '[' + fdf['sms_lag_9'].astype(str) +', ' + fdf['web_lag_9'].astype(str)  + ', '+ fdf['email_lag_9'] .astype(str) +', ' + fdf['app_lag_9'].astype(str)  + ']' 
fdf.drop(['sms_lag_9','web_lag_9','email_lag_9','app_lag_9'], axis = 1 , inplace = True)
fdf['lag_10'] = '[' + fdf['sms_lag_10'].astype(str) +', ' + fdf['web_lag_10'].astype(str)  + ', '+ fdf['email_lag_10'] .astype(str) +', ' + fdf['app_lag_10'].astype(str)  + ']' 
fdf.drop(['sms_lag_10','web_lag_10','email_lag_10','app_lag_10'], axis = 1 , inplace = True)
fdf['lag_11'] = '[' + fdf['sms_lag_11'].astype(str) +', ' + fdf['web_lag_11'].astype(str)  + ', '+ fdf['email_lag_11'] .astype(str) +', ' + fdf['app_lag_11'].astype(str)  + ']' 
fdf.drop(['sms_lag_11','web_lag_11','email_lag_11','app_lag_11'], axis = 1 , inplace = True)
fdf['lag_12'] = '[' + fdf['sms_lag_12'].astype(str) +', ' + fdf['web_lag_12'].astype(str)  + ', '+ fdf['email_lag_12'] .astype(str) +', ' + fdf['app_lag_12'].astype(str)  + ']' 
fdf.drop(['sms_lag_12','web_lag_12','email_lag_12','app_lag_12'], axis = 1 , inplace = True)
fdf['lag_13'] = '[' + fdf['sms_lag_13'].astype(str) +', ' + fdf['web_lag_13'].astype(str)  + ', '+ fdf['email_lag_13'] .astype(str) +', ' + fdf['app_lag_13'].astype(str)  + ']' 
fdf.drop(['sms_lag_13','web_lag_13','email_lag_13','app_lag_13'], axis = 1 , inplace = True)
fdf

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/inde

phone      txn_dt  txn_id          temp         lag_0         lag_1  \
0         1  2019-04-26  1233.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
1         1  2019-06-16  2642.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2         1  2019-05-09  2975.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 0]   
3         2  2019-10-09   236.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4         2  2019-10-31   681.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
...     ...         ...     ...           ...           ...           ...   
2417    999  2019-01-30  4101.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [1, 0, 0, 0]   
2418    999  2019-05-09  4665.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2419   1000  2019-01-24   241.0  [0, 0, 0, 1]  [0, 0, 0, 1]  [0, 0, 0, 0]   
2420   1000  2019-01-12  3879.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2421   1000  2019-12-29  4326.0  [1, 0, 0, 0]  [1, 0, 0, 0]  [0, 0, 0, 1]   

             lag_2         lag_3         lag_4         lag_5         lag_6  \
0     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 0]   
1     [0, 0, 0, 0]  [1, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2     [0, 0, 0, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
3     [0, 0, 0, 0]  [0, 0, 0, 0]  [1, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]   
...            ...           ...           ...           ...           ...   
2417  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2418  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2419  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2420  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2421  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   

             lag_7         lag_8         lag_9        lag_10        lag_11  \
0     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
1     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]   
3     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4     [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]   
...            ...           ...           ...           ...           ...   
2417  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2418  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2419  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2420  [0, 0, 0, 0]  [0, 0, 1, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
2421  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   

            lag_12        lag_13  
0     [0, 0, 0, 0]  [0, 0, 0, 0]  
1     [0, 0, 0, 0]  [0, 0, 0, 0]  
2     [0, 0, 0, 0]  [0, 0, 0, 0]  
3     [0, 0, 0, 0]  [0, 0, 0, 0]  
4     [0, 0, 1, 0]  [0, 0, 0, 0]  
...            ...           ...  
2417  [0, 0, 0, 0]  [0, 0, 0, 0]  
2418  [0, 0, 0, 0]  [1, 1, 0, 0]  
2419  [0, 0, 0, 0]  [0, 0, 0, 0]  
2420  [0, 0, 0, 0]  [0, 0, 0, 0]  
2421  [0, 0, 0, 0]  [0, 0, 0, 0]  

[2422 rows x 18 columns]

In [372]:
x

phone      txn_dt  txn_id          temp         lag_0         lag_1  \
3      2  2019-10-09   236.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4      2  2019-10-31   681.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
5      2  2019-02-21  1157.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]   
6      2  2019-08-11  2580.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]   
7      2  2019-12-29  2609.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
8      2  2019-02-10  4574.0  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   

          lag_2         lag_3         lag_4         lag_5         lag_6  \
3  [0, 0, 0, 0]  [0, 0, 0, 0]  [1, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]   
5  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
6  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
7  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
8  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 1, 0]   

          lag_7         lag_8         lag_9        lag_10        lag_11  \
3  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
4  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 1]   
5  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
6  [0, 0, 0, 0]  [0, 0, 0, 1]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
7  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   
8  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]  [0, 0, 0, 0]   

         lag_12        lag_13  
3  [0, 0, 0, 0]  [0, 0, 0, 0]  
4  [0, 0, 1, 0]  [0, 0, 0, 0]  
5  [0, 0, 0, 0]  [0, 0, 0, 0]  
6  [0, 0, 0, 0]  [0, 0, 0, 0]  
7  [1, 0, 0, 0]  [0, 0, 0, 1]  
8  [0, 0, 0, 0]  [0, 0, 0, 0]

In [373]:
x = fdf[fdf.phone==2]
base_transitions = numpy.zeros((4, 4))
first_act = numpy.zeros((1, 4))
conv_act =  numpy.zeros((1, 4))
for index,row in x.iterrows():
    iterx = []
    for i in range(0,14):
        #print(not np.any(eval(row.loc[('lag_'+str(i))])))
        if(np.any(eval(row.loc[('lag_'+str(i))]))):
            iterx.append(np.array(eval(row.loc[('lag_'+str(i))]), ndmin = 2))
    for i in range(0,len(iterx)-1):
            print(iterx[i].T@iterx[i+1])
            base_transitions += iterx[i].T@iterx[i+1]
    first_act += iterx[0]
    conv_act += iterx[-1]
#not np.any(a)
#row.loc[1,'lag_0']
#for i in range(0,len(iterx)):
#    print(iterx[i])
#print(base_transitions)
#conv_act
#first_act
base_transitions

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 2.]])

In [169]:
import multiprocessing
multiprocessing.cpu_count()

4

In [397]:
base_transitions = numpy.zeros((4, 4))
first_act = numpy.zeros((1, 4))
conv_act =  numpy.zeros((1, 4))
c=0
for index,row in fdf.iterrows():
    c+=1
    print(c)
    iterx = []
    for i in range(0,14):
        #print(not np.any(eval(row.loc[('lag_'+str(i))])))
        if(np.any(eval(row.loc[('lag_'+str(i))]))):
            iterx.append(np.array(eval(row.loc[('lag_'+str(i))]), ndmin = 2))
    for j in range(0,len(iterx)-1):
            base_transitions += iterx[j].T@iterx[j+1]
    first_act += iterx[0]
    conv_act += iterx[-1]
    del iterx

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136


In [379]:
print(base_transitions)
print(first_act)
print(conv_act)

[[50. 68. 68. 62.]
 [53. 71. 59. 49.]
 [77. 56. 52. 47.]
 [63. 63. 54. 62.]]
[[589. 610. 635. 657.]]
[[584. 639. 639. 637.]]


In [392]:
Transition_matrix = np.hstack((np.vstack((base_transitions,first_act)),np.vstack((conv_act.T,[0]))))
Transition_matrix

array([[ 50.,  68.,  68.,  62., 584.],
       [ 53.,  71.,  59.,  49., 639.],
       [ 77.,  56.,  52.,  47., 639.],
       [ 63.,  63.,  54.,  62., 637.],
       [589., 610., 635., 657.,   0.]])

In [395]:
tm = pd.DataFrame(Transition_matrix)
tm

0      1      2      3      4
0   50.0   68.0   68.0   62.0  584.0
1   53.0   71.0   59.0   49.0  639.0
2   77.0   56.0   52.0   47.0  639.0
3   63.0   63.0   54.0   62.0  637.0
4  589.0  610.0  635.0  657.0    0.0

In [400]:
tm.columns = ['sms','web','email','app','txn']
tm

sms    web  email    app    txn
0   50.0   68.0   68.0   62.0  584.0
1   53.0   71.0   59.0   49.0  639.0
2   77.0   56.0   52.0   47.0  639.0
3   63.0   63.0   54.0   62.0  637.0
4  589.0  610.0  635.0  657.0    0.0